language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t marcosjampietri/sciurus-marcos -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true marcosjampietri/sciurus-marcos npm test

after_success:
    - docker build -t marcosjampietri/sciurus-client ./client
    - docker build -t marcosjampietri/sciurus-nginx ./nginx


    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push marcosjampietri/sciurus-client
    - docker push marcosjampietri/sciurus-nginx

deploy:
    skip_cleanup: true
    provider: elasticbeanstalk
    region: eu-west-2
    app: sciurus-marcos
    env: Sciurusmarcos-env
    bucket_name: sciurus-bucket
    bucket_path: sciurus-marcos
    on:
        branch: main
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
