language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t marcosjampietri/sciurus-react -f ./dashboard/Dockerfile.dev ./dashboard

script:
    - docker run -e CI=true marcosjampietri/sciurus-react npm test

after_success:
    - docker build -t marcosjampietri/multi-dashboard ./dashboard
    - docker build -t marcosjampietri/multi-nginx ./nginx


    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push marcosjampietri/multi-dashboard
    - docker push marcosjampietri/multi-nginx

deploy:
    skip_cleanup: true
    provider: elasticbeanstalk
    region: eu-west-2
    app: sciurus-marcos
    env: Devopsmarcos-env
    bucket_name: elasticbeanstalk-eu-west-2-344999520177
    bucket_path: sciurus-marcos
    on:
        branch: main
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
